/* The following code was generated by JFlex 1.3.5 on 7/3/25, 2:33 PM */

  
/* --------------------------Usercode Section------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 7/3/25, 2:33 PM from the specification file
 * <tt>file:/workspace/simples/flex/simples.flex</tt>
 */
class SimplesLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  3,  0,  4,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    41,  0,  7,  0,  0,  0,  0,  0, 18, 19,  9, 13, 42, 14,  5,  8, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 12, 22, 23, 24,  0, 
     0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 20,  0, 21,  0,  6, 
     0, 29, 11, 27, 15, 25, 36, 33, 11, 16, 11, 11, 30, 34, 35, 32, 
    31, 40, 28, 26, 37, 38, 17, 11, 11, 11, 39,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    43,    86,   129,    43,   172,   215,   258,    43,    43, 
       43,    43,   301,   344,   387,    43,    43,    43,    43,   430, 
       43,    43,   473,   516,   559,   602,   645,   688,   731,   774, 
      817,    43,   860,   215,    43,   903,   946,   989,   172,  1032, 
     1075,    43,  1118,  1161,  1204,  1247,  1290,  1333,  1376,  1419, 
      172,  1462,  1505,  1548,  1591,   860,  1634,   172,  1677,  1720, 
     1763,  1806,  1849,  1892,  1935,  1978,   172,  2021,  2064,  2107, 
     2150,   172,  2193,  2236,  2279,  2322,  2365,  2408,  2451,  2494, 
     2537,  2580,  2623,   172,  2666,  2709,  2752,   172,  2795,  2838, 
     2881,   172,  2924,  2967,  3010,   172,  3053,   172,  3096,   172, 
     3139,  3182,  3225,   172,  3268,   172,  3311,  3354,   172,  3397, 
     3440,  3483,  3526,  3569,  3612,  3655,  3698,  3741,   172,  3784, 
     3827,   172,  3870,  3913,  3956,   172,  3999,   172,   172,  4042, 
      172,  4085,  4128,  4171,  4214,   172,  4257,  4300,  4343,   172, 
     4386,    43
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\2\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\5\1\6\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\6\1\31\1\32\1\33\1\34\1\35"+
    "\2\6\1\36\1\37\4\6\1\5\1\40\54\0\1\3"+
    "\3\0\1\41\50\0\1\5\50\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\20\6\2\0\7\42"+
    "\1\43\43\42\10\0\1\44\1\45\42\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\1\6\1\46\1\6\7\0"+
    "\1\47\17\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\12\6\1\50\5\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\4\6"+
    "\1\51\13\6\20\0\1\52\35\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\1\6\1\53\10\6"+
    "\1\54\5\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\1\55\17\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\1\56\17\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\14\6\1\57\3\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\1\60\17\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\3\6\1\61\1\62\13\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\15\6\1\63\2\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\64\13\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\1\6\1\65\1\6\7\0\4\6"+
    "\1\66\1\67\12\6\3\0\1\70\52\0\1\44\10\0"+
    "\2\44\3\0\3\44\7\0\21\44\1\0\10\45\1\0"+
    "\1\71\41\45\1\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\2\6\1\72\7\0\20\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\1\6\1\73\1\6\7\0"+
    "\14\6\1\74\3\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\16\6\1\75\1\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\2\6\1\76\15\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\14\6\1\77\2\6\1\100"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\12\6\1\101\5\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\14\6\1\102\3\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\1\103\17\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\1\6\1\104\1\6\7\0\20\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\7\6\1\105\10\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\1\6\1\106\1\6\1\107"+
    "\14\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\7\6\1\110\10\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\11\6\1\111"+
    "\6\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\2\6\1\112\15\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\15\6\1\113"+
    "\2\6\12\0\1\5\43\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\2\6\1\114\15\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\1\115\17\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\1\6\1\116\1\6\7\0\20\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\3\6"+
    "\1\117\14\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\4\6\1\120\13\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\15\6"+
    "\1\121\2\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\4\6\1\122\13\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\7\6"+
    "\1\123\10\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\4\6\1\124\13\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\2\6"+
    "\1\125\5\6\1\126\7\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\1\6\1\127\16\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\130\13\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\1\131\1\132\4\6"+
    "\1\133\11\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\4\6\1\134\13\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\14\6"+
    "\1\135\3\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\1\6\1\136\1\6\7\0\20\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\1\6\1\137\1\6"+
    "\7\0\20\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\7\6\1\140\10\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\1\141"+
    "\17\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\7\6\1\142\10\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\4\6\1\143"+
    "\13\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\7\6\1\144\10\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\3\6\1\145"+
    "\14\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\1\146\17\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\3\6\1\147\14\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\7\6\1\150\10\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\12\6\1\151\5\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\1\152\17\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\4\6\1\153\13\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\15\6\1\154\2\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\7\6\1\155\10\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\3\6\1\156\14\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\2\6\1\157\7\0\20\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\12\6"+
    "\1\160\5\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\12\6\1\161\5\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\1\162\2\6\7\0"+
    "\20\6\3\0\1\6\4\0\1\6\4\0\1\6\3\0"+
    "\3\6\7\0\4\6\1\163\13\6\3\0\1\6\4\0"+
    "\1\6\4\0\1\6\3\0\3\6\7\0\17\6\1\164"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\3\6\1\165\14\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\4\6\1\166\13\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\7\6\1\167\10\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\4\6\1\170\13\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\14\6\1\171\3\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\4\6\1\172\13\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\1\6"+
    "\1\173\1\6\7\0\20\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\11\6\1\174\6\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\15\6\1\175\2\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\4\6\1\176\13\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\12\6\1\177\5\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\5\6\1\200\12\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\7\6\1\201\10\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\11\6\1\202\6\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\203\13\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\4\6\1\204\13\6"+
    "\3\0\1\6\4\0\1\6\4\0\1\6\3\0\3\6"+
    "\7\0\14\6\1\205\3\6\3\0\1\6\4\0\1\6"+
    "\4\0\1\6\3\0\3\6\7\0\1\206\17\6\3\0"+
    "\1\6\4\0\1\6\4\0\1\6\3\0\3\6\7\0"+
    "\12\6\1\207\5\6\3\0\1\6\4\0\1\6\4\0"+
    "\1\6\3\0\3\6\7\0\1\210\17\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\12\6"+
    "\1\211\5\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\14\6\1\212\3\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\14\6"+
    "\1\213\3\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\7\6\1\214\10\6\3\0\1\6"+
    "\4\0\1\6\4\0\1\6\3\0\3\6\7\0\7\6"+
    "\1\215\10\6\3\0\1\6\4\0\1\6\4\0\1\6"+
    "\3\0\3\6\7\0\20\6\1\216\1\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  9,  1,  1,  1,  9,  9,  9,  9,  1,  1,  1,  9, 
     9,  9,  9,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9, 
     0,  0,  9,  1,  0,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  SimplesLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  SimplesLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4429];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 141: 
          {   return symbol(sym.PROCEDURE); }
        case 143: break;
        case 135: 
          {   return symbol(sym.DECLFLOAT); }
        case 144: break;
        case 130: 
          {   return symbol(sym.PROGRAM);   }
        case 145: break;
        case 128: 
          {   return symbol(sym.ENQUANTO);  }
        case 146: break;
        case 127: 
          {   return symbol(sym.ESCREVAL);  }
        case 147: break;
        case 125: 
          {   return symbol(sym.FIMPARA);   }
        case 148: break;
        case 121: 
          {   return symbol(sym.RETURN);    }
        case 149: break;
        case 119: 
          {   return symbol(sym.WRITELINE); }
        case 150: break;
        case 118: 
          {   return symbol(sym.DECLINT);   }
        case 151: break;
        case 108: 
          {   return symbol(sym.STARTPRG);  }
        case 152: break;
        case 105: 
          {   return symbol(sym.ENDELSE);   }
        case 153: break;
        case 31: 
          {   return symbol(sym.COMMA);     }
        case 154: break;
        case 22: 
          {   return symbol(sym.E);         }
        case 155: break;
        case 21: 
          {   return symbol(sym.GREATER);   }
        case 156: break;
        case 20: 
          {   return symbol(sym.EQUALS);    }
        case 157: break;
        case 19: 
          {   return symbol(sym.LESS);      }
        case 158: break;
        case 18: 
          {   return symbol(sym.RBRCKT);    }
        case 159: break;
        case 17: 
          {   return symbol(sym.LBRCKT);    }
        case 160: break;
        case 16: 
          {   return symbol(sym.RPAREN);    }
        case 161: break;
        case 15: 
          {   return symbol(sym.LPAREN);    }
        case 162: break;
        case 8: 
          {   return symbol(sym.TIMES);     }
        case 163: break;
        case 9: 
          {   return symbol(sym.SEMI);      }
        case 164: break;
        case 10: 
          {   return symbol(sym.PLUS);      }
        case 165: break;
        case 11: 
          {   return symbol(sym.MINUS);     }
        case 166: break;
        case 38: 
          {   return symbol(sym.DE);        }
        case 167: break;
        case 41: 
          {   return symbol(sym.ASSIGN);    }
        case 168: break;
        case 44: 
          {   return symbol(sym.IFF);       }
        case 169: break;
        case 50: 
          {   return symbol(sym.OU);        }
        case 170: break;
        case 57: 
          {   return symbol(sym.DIVIDE);    }
        case 171: break;
        case 66: 
          {   return symbol(sym.ATE);       }
        case 172: break;
        case 71: 
          {   return symbol(sym.NAO);       }
        case 173: break;
        case 72: 
          {   return symbol(sym.ENDPRG);    }
        case 174: break;
        case 83: 
          {   return symbol(sym.READLINE);  }
        case 175: break;
        case 87: 
          {   return symbol(sym.PARA);      }
        case 176: break;
        case 91: 
          {   return symbol(sym.FACA);      }
        case 177: break;
        case 95: 
          {   return symbol(sym.VOID);      }
        case 178: break;
        case 97: 
          {   return symbol(sym.THENN);     }
        case 179: break;
        case 99: 
          {   return symbol(sym.ELSEE);     }
        case 180: break;
        case 103: 
          {   return symbol(sym.PASSO);     }
        case 181: break;
        case 3: 
        case 4: 
          {  /* just skip what was found, do nothing */  }
        case 182: break;
        case 35: 
          {  /* just skip what was found, do nothing */  }
        case 183: break;
        case 5: 
        case 12: 
        case 13: 
        case 14: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 30: 
        case 37: 
        case 39: 
        case 40: 
        case 42: 
        case 43: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 85: 
        case 86: 
        case 88: 
        case 89: 
        case 90: 
        case 92: 
        case 93: 
        case 94: 
        case 96: 
        case 98: 
        case 100: 
        case 101: 
        case 102: 
        case 104: 
        case 106: 
        case 107: 
        case 109: 
        case 110: 
        case 111: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 116: 
        case 117: 
        case 120: 
        case 122: 
        case 123: 
        case 124: 
        case 126: 
        case 129: 
        case 131: 
        case 132: 
        case 133: 
        case 134: 
        case 136: 
        case 137: 
        case 138: 
        case 140: 
          {  return symbol(sym.ID, yytext()); }
        case 184: break;
        case 34: 
          {  return symbol(sym.TEXTO, yytext().substring(1, yytext().length() - 1));  }
        case 185: break;
        case 139: 
          {   return symbol(sym.FIMENQUANTO); }
        case 186: break;
        case 2: 
          {  return symbol(sym.INTT,yytext());  }
        case 187: break;
        case 1: 
        case 6: 
        case 7: 
          {  System.err.println("Error: Caracter Ilegal <"+yytext()+"> na linha: " + yyline);  }
        case 188: break;
        case 55: 
          {  return symbol(sym.FLOATT, yytext());  }
        case 189: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
